### ISSUE TITLE
JSDoc or similar documentation for inferred types?

### ISSUE THREAD

**Issue by natesilva** [vriad/zod#200] opened 2020-10-26 17:55 UTC
Is there a way to provide JSDoc (or some kind of documentation) attached to the inferred types?

**Comment by vriad** [comment] 2020-10-27 20:11
I'm afraid I'm not very familiar with JSDoc or how to use it with TypeScript

**Comment by vriad** [comment] 2020-10-29 19:43
After doing some reading on the subject it's doesn't appear that JSDoc and TypeScript are compatible at all. Looks like [TypeDoc](https://typedoc.org/guides/installation/) might be a better solution. Though it appears TypeDoc also doesn't support annotating `type` aliases, only `interface`s... 🤷‍♂️

Anyway, I'm gonna close this since this is out of scope for Zod.

**Closed by vriad** 2020-10-29 19:43 UTC

**Comment by natesilva** [comment] 2020-10-29 21:12
It would be nice to have pop-up documentation for interface properties in VS Code. Typically we use the format shown in examples on the TypeScript web site (what I thought was JSDoc, but might actually be [TSDoc](https://github.com/Microsoft/tsdoc)). VS Code recognizes that, and it is included in exported modules. Anyway, it sounds like this isn’t possible right now. Thank you for looking into it.

**Comment by BurtHarris** [comment] 2020-11-20 20:40
The TypeScript _does_ understand JSDoc (not TSDoc), but you won't find it in the language specification.   This mostly in the [_TypeScript language service_](https://github.com/microsoft/TypeScript/tree/master/src/server), rather than in the compiler itself, but the compiler and language service ship in the same package.   The language service is used by IDEs (including Visual Studio Code and others) to provide [IntelliSense](https://code.visualstudio.com/docs/typescript/typescript-tutorial#_intellisense) at code editing time to enhance the developer experience when writing in javascript or TypeScript

In my initial experiments with zod, the IntelliSense experience was less than good, and this could be enhanced by adding some fairly simple JSDoc comments to the zod source code, this would mostly help when someone is trying to write a zod schema, e.g. when I type "`z.`", it would enhance the list of hints provided.   Adding these JSDoc comments to zod's source code would be fairly simple.  I can provide a PR that gets that started adding JSDoc comments to frequently-used members like `z.string() `and, `z.object()`.

But this issue seems to be asking for more than that, adding IntelliSense to the `infer`ed types seems like a much trickier proposition.

**Comment by tonyxiao** [comment] 2022-06-22 09:23
Any updates on this one since 2020? This is one of the main thing that holds me back from moving everything to zod - inability to have comments associate with types.

**Comment by lorefnon** [comment] 2022-06-25 10:02
@tonyxiao A workaround that has worked well for me is defining interfaces that extend types extracted from  zod types and then documenting them through typedoc. [This post](https://lorefnon.me/2022/06/25/generating-api-docs-for-zod-types/) has a few examples. It has caveats but mostly works well in practice - [this library](https://github.com/lorefnon/ts-sql-codegen) has its [documentation](https://github.com/lorefnon/ts-sql-codegen/blob/main/docs/classes/Generator.md) generated in this manner.

**Comment by ian-schu** [comment] 2022-07-28 21:25
@lorefnon thanks for the very helpful post. I wandered in here and was hoping your solution might work for me. I don't use a doc generator such as TypeDoc, but hoped your approach might enable intellisense in VS Code, which is what I'm after.

Perhaps TypeDoc uses a different mechanism from the VS Code language server? Anyway, here's my trivial reproduction, with intellisense failing to show inline documentation for the `name` property. Can you confirm this is / is not what you'd expect here?

![image](https://user-images.githubusercontent.com/34523645/181640278-fa83d58c-5038-4ec6-b0fb-c52da420ff9c.png)

Before seeing your post, I was in the habit of doing this:

```ts
type User = z.infer<typeof UserSchema>
```

... Which as you know, also doesn't work 😏 

Thanks for any extra commentary you can provide.

**Comment by lorefnon** [comment] 2022-07-29 06:21
@ian-schu That is strange because it does work for me. 

![image](https://user-images.githubusercontent.com/1449492/181695654-b3ad9361-21e0-4330-89ee-a63fb5d0d3ae.png)

`z.infer` is fine too. Only reason I used interfaces is because typedoc skips arbitrary type aliases by default. 

If you could share this snippet in a gist/repo I can try to reproduce locally.

**Comment by ian-schu** [comment] 2022-08-24 11:29
Thanks @lorefnon for the quick reply, and sorry it's taken me so long to get back to this. Good news: I think you're right. I cannot reproduce the original problem. When I try, my TSDoc gets replicated to the inferred type without any problem:

![image](https://user-images.githubusercontent.com/34523645/186407550-bf9249fe-bc04-4092-8606-e4b2d84ac170.png)

**Comment by joeledwardson** [comment] 2022-08-24 15:19
> @tonyxiao A workaround that has worked well for me is defining interfaces that extend types extracted from zod types and then documenting them through typedoc. [This post](https://lorefnon.me/2022/06/25/generating-api-docs-for-zod-types/) has a few examples. It has caveats but mostly works well in practice - [this library](https://github.com/lorefnon/ts-sql-codegen) has its [documentation](https://github.com/lorefnon/ts-sql-codegen/blob/main/docs/classes/Generator.md) generated in this manner.

Has there been any advance on this? I am trying to export zod using typedoc but as it mentions in the post it doesnt work with unions or intersections

**Comment by razb-viola** [comment] 2023-11-03 12:27
Yes but when you have some case like this:

```
const age = registry.register('age', 
  /**
   * Info about age
   */
  z.number()
  .min(15)
  .max(20)
  .openapi({ 
    example: 18, 
    'x-faker': 'number.int({ "min": 1, "max": 20 })',
    description: 'some desc here' 
  })
)
export type Age = z.infer<typeof age>

const UserSchema = registry
.register('User', z.object({
  name,
  age
}))
export type User = z.infer<typeof UserSchema>
```

as you can see the age is referenced in the UserSchema object. Then you won't get the comment of typedoc/jsdoc.

Can we do something to make it work as well?

**Comment by JacobDanton** [comment] 2024-02-07 04:50
Since this comes up as the top google result for `zod jsdoc`, I thought I would add the actual answer here.

Given a schema:
```
export const TaskSchema = z.object({
    ...
});
```

Define the inferred type with:
```
/** @typedef { z.infer<typeof TaskSchema> } Task */
```

**Comment by lorefnon** [comment] 2024-02-07 07:56
@JacobDanton This is fine if you are using jsdoc comments for typechecking in js files. 

But for documentation generation (the primary purpose of jsdoc) it is not useful at all because it does not convey anything about the shape of the expected structure to the API consumer looking at the generated documentation.

**Comment by JacobDanton** [comment] 2024-02-07 14:09
@lorefnon  It does in my testing. For example, if I have:
``` js
export const MyTestSchema = z.object({
  /** This is a foo */
  foo: z.string(),
});

/** @typedef { z.infer<typeof MyTestSchema> } MyTest */

/** @type {MyTest} */
const test = { foo: "foo" }
```

Then on hovering over `test.foo`, I get:
![image](https://github.com/colinhacks/zod/assets/820092/2aa0071d-e2f1-4973-9dbf-e223d7d6786c)

**Comment by LeonGeldsch** [comment] 2025-08-06 11:29
I would also support adding small comments to the most used functions. For example adding a small note on what the default regex being used for `email()` is.

For example you could just take the explanation from the docs and add it there (maybe in a shortened form).

### Example:

```TS
To validate email addresses.
By default, Zod uses a comparatively strict email regex designed to validate normal email addresses containing common characters. It's roughly equivalent to the rules enforced by Gmail.
```
Add the above as a JSDocs/TSDocs comment so it shows up on hover here (sorry for lightmode):

<img width="232" height="52" alt="Image" src="https://github.com/user-attachments/assets/bdfc2e39-3546-4f0a-b70b-76fd09ee0674" />
