### ISSUE TITLE
[Feature Request]: Ability to provide a message to types

### ISSUE THREAD

**Issue by enricoschaaf** [vriad/zod#178] opened 2020-10-01 18:05 UTC
I am currently using Blitz.js which uses zod for validation on the server and on the client. Everything works perfectly exept one small thing. When I want to customize the error message "Required" that is thrown by z.string() or other similar functions, there is not a good way to to it. With min() i can just provide the message as a prop, for z.string() I either have to provide a custom ZodErrorMap or avoid using zod for this. Would it be possible to change the string method to exept a message prop like this?
```typescript
z.string({message: "Email is a required field."})
```
or
```typescript
z.string("Email is a required field.")
```

**Comment by vriad** [comment] 2020-10-16 04:23
This is a duplicate of #97, so I'm gonna close for now. This is on the roadmap.

**Closed by vriad** 2020-10-16 04:23 UTC
