### ISSUE TITLE
Path is not being appended from `.refine` to custom `errorMap`

### ISSUE THREAD

**Issue by ervasive** [vriad/zod#129] opened 2020-08-29 23:04 UTC
Hello

It looks like there is a problem with custom validation with `refine` method when the provided `path` elements are not being appended to the resulting path within a custom error map function.

I figured that it would be easier to demonstrate the issue with a screenshot and a [live demo](https://codesandbox.io/s/zod-path-error-map-demo-wpiob).

So on line `6` we have a custom validation that specifies additional path elements on validation failure.
On line `16` we print the passed `path` value to the console which is expected to be `["items", "items-too-few"]` but we get `["items"]`
In addition on line `37` we display the `ZodError` errors array which has the correct (expected) path elements.

![image](https://user-images.githubusercontent.com/85254/91647289-d84eed80-ea61-11ea-9183-ae611881ec53.png)

Also, it looks like the error map function is not being called at all if the `refine` params object specifies `message` property, but that is a separate issue, let me know if I should open another one.

Thank you for the great library

**Comment by vriad** [comment] 2020-08-30 08:30
Good catch! Thanks for the detailed writeup. I'll look into this as soon as I can.

> error map function is not being called at all if the refine params object specifies message property

This is currently the intended behavior. Passing in a message there is designed to short-circuit Zod's built-in error message system.

**Comment by ervasive** [comment] 2020-08-30 10:27
> > 
> 
> This is currently the intended behavior. Passing in a message there is designed to short-circuit Zod's built-in error message system.

Ahh, got it, seems reasonable

**Comment by vriad** [comment] 2020-09-01 22:42
Fixed in zod@1.11.4 - and added as a test case :) 👍

**Closed** 2020-09-01 22:42 UTC
