### ISSUE TITLE
Is published package not transpiled?

### ISSUE THREAD

**Issue by ospfranco** [vriad/zod#9] opened 2020-03-13 19:33 UTC
I'm developing a aws lambda based application, that means I cannot direcly use typescript code when deploying, when I tried to deploy a lambda using zod, my webpack process failed with the following error:

```
Error: TypeScript emitted no output for /Users/osp/dev/strestsaas/server/node_modules/zod/index.ts. By default, ts-loader will not compile .ts files in node_modules.
You should not need to recompile .ts files there, but if you really want to, use the allowTsInNodeModules option.
```

I think the published version of the package should not directly link to .ts files in order for transpiled projects to work, right?

**Comment by ospfranco** [comment] 2020-03-13 19:36
btw, this is a cool project, saw it on hacker-news, but after playing around for a few minutes I can tell there's still a lot to be done before replacing with joi or yup, maybe I will try to submit a PR if I have the time.

**Comment by vriad** [comment] 2020-03-13 19:44
Yeah, working on this now - didn't think there would be this much interest, so I didn't follow best practices initially. Gonna have enum and literal support ready by the end of the day. 

Closing this for now since it's a duplicate of https://github.com/vriad/zod/issues/7 

And PRs are of course hugely appreciated :) If there are specific joi/yup features you're looking for, by all means create an issue and I'll get around to it.

**Closed by vriad** 2020-03-13 19:44 UTC

**Comment by vriad** [comment] 2020-03-14 07:00
@ospfranco The package is now transpiled, let me know if you still have any issues 👍
